apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-service-deployment
  labels:
    app: movie-info-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info-service-deployment
  template:
    metadata:
      labels:
        app: movie-info-service-deployment
    spec:
      containers:
      - name: movie-info-service-deployment
        image: giridharaguptha/ticket-booking-movie-info-service:1.0.0
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: movie-info-service
spec:
  selector:
    app: movie-info-service-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
